---
title: "Project One"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## MT5763 Software and Data Analysis **Due: 8th October**

Please find my GitHub repo here <https://github.com/selsiekiely/MT5763_1_190018562>.

### **Contents**
### Data Wrangling
###Data Visualisation
###Statistical Modelling

##**Data Wrangling**
## We will now data wrangle the BikeSeoul.csv

```{r, include = FALSE}
library(tidyverse)
library(readr)
BikeSeoul <- read_csv("~/Year 3/MT5763/BikeSeoul.csv")
```

```{r BikeSeoul}
BikeSeoul <- BikeSeoul %>%
  select(-`Visibility (10m)`, -`Dew point temperature(C)`, -`Solar Radiation (MJ/m2)`, 
         -`Rainfall(mm)`, -`Snowfall (cm)`)
BikeSeoul <- BikeSeoul %>%  
  filter(!is.na(`Rented Bike Count`))
View(BikeSeoul)
BikeSeoul <- BikeSeoul %>% 
  select(-`Functioning Day`)
library(lubridate)
BikeSeoul <- BikeSeoul %>%
  rename(Count = `Rented Bike Count`) %>%
  rename(Temperature = `Temperature(C)`) %>%
  rename(Humidity = `Humidity(%)`) %>%
  rename(WindSpeed = `Wind speed (m/s)`) %>%
  rename(Season = `Seasons`) #%>%
BikeSeoul$Date <- as.Date(BikeSeoul$Date)
BikeSeoul <- BikeSeoul %>%
  mutate(BikeSeoul, FullDate = make_datetime(year = year(Date), month = month(Date), day = mday(Date), Hour))
#BikeSeoul <- BikeSeoul %>%
 # rename(Holiday, c("Holiday" = "Yes")) %>%
  #rename(Holiday, c("No Holiday" = "No"))
```
```{r, include = FALSE}
BikeWashington <- read_csv("~/Year 3/MT5763/BikeWashingtonDC.csv")
BikeWashington <- BikeWashington %>%
  select(-instant, -yr, -mnth, -weekday, -workingday, -weathersit, -atemp, -casual, -registered)
BikeWashington <- BikeWashington %>%
  rename(Date = dteday) %>%
  rename(Count = cnt) %>%
  rename(Hour = hr) %>%
  rename(Temperature = temp) %>%
  rename(Humidity = hum) %>%
  rename(WindSpeed = windspeed) %>%
  rename(Season = season) %>%
  rename(Holiday = holiday)
View(BikeWashington)

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
